/**
 * PaintDepotApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { UpdateUserStatusDto } from '../model/models';
import { UserDtoApiResponseDto } from '../model/models';
import { UserDtoListApiResponseDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminUsersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/admin/users
     * @param pageNumber 
     * @param pageSize 
     * @param search 
     */
    apiAdminUsersGet(pageNumber?: number, pageSize?: number, search?: string, extraHttpRequestParams?: any): Observable<UserDtoListApiResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/admin/users/{id}
     * @param id 
     */
    apiAdminUsersIdGet(id: number, extraHttpRequestParams?: any): Observable<UserDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/admin/users/{id}/status
     * @param id 
     * @param updateUserStatusDto 
     */
    apiAdminUsersIdStatusPut(id: number, updateUserStatusDto?: UpdateUserStatusDto, extraHttpRequestParams?: any): Observable<UserDtoApiResponseDto>;

}
