/**
 * PaintDepotApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { OrderDetailDtoApiResponseDto } from '../model/models';
import { OrderDtoListApiResponseDto } from '../model/models';
import { SalesAnalyticsDtoApiResponseDto } from '../model/models';
import { UpdateOrderStatusDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminOrdersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/admin/orders/analytics/sales
     * @param startDate 
     * @param endDate 
     */
    apiAdminOrdersAnalyticsSalesGet(startDate?: string, endDate?: string, extraHttpRequestParams?: any): Observable<SalesAnalyticsDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/admin/orders
     * @param pageNumber 
     * @param pageSize 
     */
    apiAdminOrdersGet(pageNumber?: number, pageSize?: number, extraHttpRequestParams?: any): Observable<OrderDtoListApiResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/admin/orders/{id}
     * @param id 
     */
    apiAdminOrdersIdGet(id: number, extraHttpRequestParams?: any): Observable<OrderDetailDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/admin/orders/{id}/status
     * @param id 
     * @param updateOrderStatusDto 
     */
    apiAdminOrdersIdStatusPut(id: number, updateOrderStatusDto?: UpdateOrderStatusDto, extraHttpRequestParams?: any): Observable<OrderDetailDtoApiResponseDto>;

}
