/**
 * PaintDepotApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ObjectApiResponseDto } from '../model/models';
import { ReviewDtoApiResponseDto } from '../model/models';
import { ReviewDtoListApiResponseDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminReviewsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/admin/reviews
     * @param status 
     * @param rating 
     * @param pageNumber 
     * @param pageSize 
     */
    apiAdminReviewsGet(status?: string, rating?: number, pageNumber?: number, pageSize?: number, extraHttpRequestParams?: any): Observable<ReviewDtoListApiResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/admin/reviews/{id}/reject
     * @param id 
     */
    apiAdminReviewsIdRejectPut(id: number, extraHttpRequestParams?: any): Observable<ReviewDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/admin/reviews/statistics
     */
    apiAdminReviewsStatisticsGet(extraHttpRequestParams?: any): Observable<ObjectApiResponseDto>;

}
