/**
 * PaintDepotApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateProductDto } from '../model/models';
import { CreateProductVariantDto } from '../model/models';
import { ObjectApiResponseDto } from '../model/models';
import { ProductDetailDtoApiResponseDto } from '../model/models';
import { ProductDtoPaginatedResponseDto } from '../model/models';
import { ProductImageDtoApiResponseDto } from '../model/models';
import { ProductVariantDtoApiResponseDto } from '../model/models';
import { UpdateProductDto } from '../model/models';
import { UpdateProductVariantDto } from '../model/models';
import { UpdateStockDto } from '../model/models';
import { UploadProductImageDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminProductsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/admin/products
     * @param pageNumber 
     * @param pageSize 
     * @param search 
     * @param categoryId 
     * @param brandId 
     */
    apiAdminProductsGet(pageNumber?: number, pageSize?: number, search?: string, categoryId?: number, brandId?: number, extraHttpRequestParams?: any): Observable<ProductDtoPaginatedResponseDto>;

    /**
     * 
     * 
     * @endpoint delete /api/admin/products/{id}
     * @param id 
     */
    apiAdminProductsIdDelete(id: number, extraHttpRequestParams?: any): Observable<ObjectApiResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/admin/products/{id}
     * @param id 
     */
    apiAdminProductsIdGet(id: number, extraHttpRequestParams?: any): Observable<ProductDetailDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint delete /api/admin/products/{id}/images/{imageId}
     * @param id 
     * @param imageId 
     */
    apiAdminProductsIdImagesImageIdDelete(id: number, imageId: number, extraHttpRequestParams?: any): Observable<ObjectApiResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/admin/products/{id}/images/{imageId}
     * @param id 
     * @param imageId 
     * @param uploadProductImageDto 
     */
    apiAdminProductsIdImagesImageIdPut(id: number, imageId: number, uploadProductImageDto?: UploadProductImageDto, extraHttpRequestParams?: any): Observable<ProductImageDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/admin/products/{id}/images
     * @param id 
     * @param uploadProductImageDto 
     */
    apiAdminProductsIdImagesPost(id: number, uploadProductImageDto?: UploadProductImageDto, extraHttpRequestParams?: any): Observable<ProductImageDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/admin/products/{id}
     * @param id 
     * @param updateProductDto 
     */
    apiAdminProductsIdPut(id: number, updateProductDto?: UpdateProductDto, extraHttpRequestParams?: any): Observable<ProductDetailDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/admin/products/{id}/stock
     * @param id 
     * @param updateStockDto 
     */
    apiAdminProductsIdStockPut(id: number, updateStockDto?: UpdateStockDto, extraHttpRequestParams?: any): Observable<ObjectApiResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/admin/products/{id}/variants
     * @param id 
     * @param createProductVariantDto 
     */
    apiAdminProductsIdVariantsPost(id: number, createProductVariantDto?: CreateProductVariantDto, extraHttpRequestParams?: any): Observable<ProductVariantDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint delete /api/admin/products/{id}/variants/{variantId}
     * @param id 
     * @param variantId 
     */
    apiAdminProductsIdVariantsVariantIdDelete(id: number, variantId: number, extraHttpRequestParams?: any): Observable<ObjectApiResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/admin/products/{id}/variants/{variantId}
     * @param id 
     * @param variantId 
     * @param updateProductVariantDto 
     */
    apiAdminProductsIdVariantsVariantIdPut(id: number, variantId: number, updateProductVariantDto?: UpdateProductVariantDto, extraHttpRequestParams?: any): Observable<ProductVariantDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/admin/products
     * @param createProductDto 
     */
    apiAdminProductsPost(createProductDto?: CreateProductDto, extraHttpRequestParams?: any): Observable<ProductDetailDtoApiResponseDto>;

}
