/**
 * PaintDepotApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CouponDtoApiResponseDto } from '../model/models';
import { CreateCouponDto } from '../model/models';
import { ObjectApiResponseDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminCouponsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint delete /api/admin/coupons/{id}
     * @param id 
     */
    apiAdminCouponsIdDelete(id: number, extraHttpRequestParams?: any): Observable<ObjectApiResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/admin/coupons/{id}
     * @param id 
     * @param createCouponDto 
     */
    apiAdminCouponsIdPut(id: number, createCouponDto?: CreateCouponDto, extraHttpRequestParams?: any): Observable<CouponDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/admin/coupons
     * @param createCouponDto 
     */
    apiAdminCouponsPost(createCouponDto?: CreateCouponDto, extraHttpRequestParams?: any): Observable<CouponDtoApiResponseDto>;

}
