export * from './adminCoupons.service';
import { AdminCouponsService } from './adminCoupons.service';
export * from './adminCoupons.serviceInterface';
export * from './adminOrders.service';
import { AdminOrdersService } from './adminOrders.service';
export * from './adminOrders.serviceInterface';
export * from './adminProducts.service';
import { AdminProductsService } from './adminProducts.service';
export * from './adminProducts.serviceInterface';
export * from './adminReviews.service';
import { AdminReviewsService } from './adminReviews.service';
export * from './adminReviews.serviceInterface';
export * from './adminUsers.service';
import { AdminUsersService } from './adminUsers.service';
export * from './adminUsers.serviceInterface';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './brands.service';
import { BrandsService } from './brands.service';
export * from './brands.serviceInterface';
export * from './cart.service';
import { CartService } from './cart.service';
export * from './cart.serviceInterface';
export * from './categories.service';
import { CategoriesService } from './categories.service';
export * from './categories.serviceInterface';
export * from './coupons.service';
import { CouponsService } from './coupons.service';
export * from './coupons.serviceInterface';
export * from './images.service';
import { ImagesService } from './images.service';
export * from './images.serviceInterface';
export * from './orders.service';
import { OrdersService } from './orders.service';
export * from './orders.serviceInterface';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './products.serviceInterface';
export * from './reviews.service';
import { ReviewsService } from './reviews.service';
export * from './reviews.serviceInterface';
export * from './shipping.service';
import { ShippingService } from './shipping.service';
export * from './shipping.serviceInterface';
export * from './upload.service';
import { UploadService } from './upload.service';
export * from './upload.serviceInterface';
export * from './wishlist.service';
import { WishlistService } from './wishlist.service';
export * from './wishlist.serviceInterface';
export const APIS = [AdminCouponsService, AdminOrdersService, AdminProductsService, AdminReviewsService, AdminUsersService, AuthService, BrandsService, CartService, CategoriesService, CouponsService, ImagesService, OrdersService, ProductsService, ReviewsService, ShippingService, UploadService, WishlistService];
