/**
 * PaintDepotApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { LoginDto } from '../model/models';
import { LoginResponseDtoApiResponseDto } from '../model/models';
import { ObjectApiResponseDto } from '../model/models';
import { RegisterDto } from '../model/models';
import { UserDtoApiResponseDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/Auth/login
     * @param loginDto 
     */
    apiAuthLoginPost(loginDto?: LoginDto, extraHttpRequestParams?: any): Observable<LoginResponseDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/Auth/register
     * @param registerDto 
     */
    apiAuthRegisterPost(registerDto?: RegisterDto, extraHttpRequestParams?: any): Observable<UserDtoApiResponseDto>;

}
