/**
 * PaintDepotApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BrandDtoApiResponseDto } from '../model/models';
import { BrandDtoListApiResponseDto } from '../model/models';
import { CreateBrandDto } from '../model/models';
import { ObjectApiResponseDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BrandsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/Brands
     * @param includeInactive 
     */
    apiBrandsGet(includeInactive?: boolean, extraHttpRequestParams?: any): Observable<BrandDtoListApiResponseDto>;

    /**
     * 
     * 
     * @endpoint delete /api/Brands/{id}
     * @param id 
     */
    apiBrandsIdDelete(id: number, extraHttpRequestParams?: any): Observable<ObjectApiResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/Brands/{id}
     * @param id 
     */
    apiBrandsIdGet(id: number, extraHttpRequestParams?: any): Observable<BrandDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/Brands/{id}
     * @param id 
     * @param createBrandDto 
     */
    apiBrandsIdPut(id: number, createBrandDto?: CreateBrandDto, extraHttpRequestParams?: any): Observable<BrandDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/Brands
     * @param createBrandDto 
     */
    apiBrandsPost(createBrandDto?: CreateBrandDto, extraHttpRequestParams?: any): Observable<BrandDtoApiResponseDto>;

}
