/**
 * PaintDepotApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AddToCartDto } from '../model/models';
import { CartDtoApiResponseDto } from '../model/models';
import { ObjectApiResponseDto } from '../model/models';
import { UpdateCartItemDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CartServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint delete /api/cart
     */
    apiCartDelete(extraHttpRequestParams?: any): Observable<ObjectApiResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/cart
     */
    apiCartGet(extraHttpRequestParams?: any): Observable<CartDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint delete /api/cart/items/{id}
     * @param id 
     */
    apiCartItemsIdDelete(id: number, extraHttpRequestParams?: any): Observable<ObjectApiResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/cart/items/{id}
     * @param id 
     * @param updateCartItemDto 
     */
    apiCartItemsIdPut(id: number, updateCartItemDto?: UpdateCartItemDto, extraHttpRequestParams?: any): Observable<CartDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/cart/items
     * @param addToCartDto 
     */
    apiCartItemsPost(addToCartDto?: AddToCartDto, extraHttpRequestParams?: any): Observable<CartDtoApiResponseDto>;

}
