/**
 * PaintDepotApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CategoryDtoApiResponseDto } from '../model/models';
import { CategoryDtoListApiResponseDto } from '../model/models';
import { CreateCategoryDto } from '../model/models';
import { ObjectApiResponseDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CategoriesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/Categories
     * @param includeInactive 
     */
    apiCategoriesGet(includeInactive?: boolean, extraHttpRequestParams?: any): Observable<CategoryDtoListApiResponseDto>;

    /**
     * 
     * 
     * @endpoint delete /api/Categories/{id}
     * @param id 
     */
    apiCategoriesIdDelete(id: number, extraHttpRequestParams?: any): Observable<ObjectApiResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/Categories/{id}
     * @param id 
     */
    apiCategoriesIdGet(id: number, extraHttpRequestParams?: any): Observable<CategoryDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/Categories/{id}
     * @param id 
     * @param createCategoryDto 
     */
    apiCategoriesIdPut(id: number, createCategoryDto?: CreateCategoryDto, extraHttpRequestParams?: any): Observable<CategoryDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/Categories
     * @param createCategoryDto 
     */
    apiCategoriesPost(createCategoryDto?: CreateCategoryDto, extraHttpRequestParams?: any): Observable<CategoryDtoApiResponseDto>;

}
