/**
 * PaintDepotApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateGalleryImageDto } from '../model/models';
import { GalleryImageDtoApiResponseDto } from '../model/models';
import { GalleryImageDtoPaginatedResponseDto } from '../model/models';
import { ObjectApiResponseDto } from '../model/models';
import { StringListApiResponseDto } from '../model/models';
import { UpdateGalleryImageDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface GalleryServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/Gallery/admin
     * @param page 
     * @param pageSize 
     * @param category 
     * @param isFeatured 
     */
    apiGalleryAdminGet(page?: number, pageSize?: number, category?: string, isFeatured?: boolean, extraHttpRequestParams?: any): Observable<GalleryImageDtoPaginatedResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/Gallery/categories
     */
    apiGalleryCategoriesGet(extraHttpRequestParams?: any): Observable<StringListApiResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/Gallery
     * @param page 
     * @param pageSize 
     * @param category 
     * @param isFeatured 
     */
    apiGalleryGet(page?: number, pageSize?: number, category?: string, isFeatured?: boolean, extraHttpRequestParams?: any): Observable<GalleryImageDtoPaginatedResponseDto>;

    /**
     * 
     * 
     * @endpoint delete /api/Gallery/{id}
     * @param id 
     */
    apiGalleryIdDelete(id: number, extraHttpRequestParams?: any): Observable<ObjectApiResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/Gallery/{id}
     * @param id 
     */
    apiGalleryIdGet(id: number, extraHttpRequestParams?: any): Observable<GalleryImageDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/Gallery/{id}
     * @param id 
     * @param updateGalleryImageDto 
     */
    apiGalleryIdPut(id: number, updateGalleryImageDto?: UpdateGalleryImageDto, extraHttpRequestParams?: any): Observable<GalleryImageDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint patch /api/Gallery/{id}/toggle-active
     * @param id 
     */
    apiGalleryIdToggleActivePatch(id: number, extraHttpRequestParams?: any): Observable<ObjectApiResponseDto>;

    /**
     * 
     * 
     * @endpoint patch /api/Gallery/{id}/toggle-featured
     * @param id 
     */
    apiGalleryIdToggleFeaturedPatch(id: number, extraHttpRequestParams?: any): Observable<ObjectApiResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/Gallery
     * @param createGalleryImageDto 
     */
    apiGalleryPost(createGalleryImageDto?: CreateGalleryImageDto, extraHttpRequestParams?: any): Observable<GalleryImageDtoApiResponseDto>;

}
