/**
 * PaintDepotApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateOrderDto } from '../model/models';
import { ObjectApiResponseDto } from '../model/models';
import { OrderDetailDtoApiResponseDto } from '../model/models';
import { OrderDtoListApiResponseDto } from '../model/models';
import { UpdateOrderStatusDto } from '../model/models';
import { UploadPaymentSlipDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface OrdersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/orders
     */
    apiOrdersGet(extraHttpRequestParams?: any): Observable<OrderDtoListApiResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/orders/{id}/cancel
     * @param id 
     */
    apiOrdersIdCancelPut(id: number, extraHttpRequestParams?: any): Observable<ObjectApiResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/orders/{id}
     * @param id 
     */
    apiOrdersIdGet(id: number, extraHttpRequestParams?: any): Observable<OrderDetailDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/orders/{id}/payment-slip
     * @param id 
     * @param uploadPaymentSlipDto 
     */
    apiOrdersIdPaymentSlipPut(id: number, uploadPaymentSlipDto?: UploadPaymentSlipDto, extraHttpRequestParams?: any): Observable<OrderDetailDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/orders/{id}/status
     * @param id 
     * @param updateOrderStatusDto 
     */
    apiOrdersIdStatusPut(id: number, updateOrderStatusDto?: UpdateOrderStatusDto, extraHttpRequestParams?: any): Observable<OrderDetailDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/orders
     * @param createOrderDto 
     */
    apiOrdersPost(createOrderDto?: CreateOrderDto, extraHttpRequestParams?: any): Observable<OrderDetailDtoApiResponseDto>;

}
