/**
 * PaintDepotApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateProductDto } from '../model/models';
import { ObjectApiResponseDto } from '../model/models';
import { ProductDetailDtoApiResponseDto } from '../model/models';
import { ProductDtoPaginatedResponseDtoApiResponseDto } from '../model/models';
import { UpdateProductDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ProductsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/Products
     * @param page 
     * @param pageSize 
     * @param search 
     * @param categoryId 
     * @param brandId 
     * @param isFeatured 
     * @param isBestseller 
     * @param isNewArrival 
     * @param minPrice 
     * @param maxPrice 
     * @param sortBy 
     */
    apiProductsGet(page?: number, pageSize?: number, search?: string, categoryId?: number, brandId?: number, isFeatured?: boolean, isBestseller?: boolean, isNewArrival?: boolean, minPrice?: number, maxPrice?: number, sortBy?: string, extraHttpRequestParams?: any): Observable<ProductDtoPaginatedResponseDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint delete /api/Products/{id}
     * @param id 
     */
    apiProductsIdDelete(id: number, extraHttpRequestParams?: any): Observable<ObjectApiResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/Products/{id}
     * @param id 
     */
    apiProductsIdGet(id: number, extraHttpRequestParams?: any): Observable<ProductDetailDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/Products/{id}
     * @param id 
     * @param updateProductDto 
     */
    apiProductsIdPut(id: number, updateProductDto?: UpdateProductDto, extraHttpRequestParams?: any): Observable<ProductDetailDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/Products
     * @param createProductDto 
     */
    apiProductsPost(createProductDto?: CreateProductDto, extraHttpRequestParams?: any): Observable<ProductDetailDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/Products/slug/{slug}
     * @param slug 
     */
    apiProductsSlugSlugGet(slug: string, extraHttpRequestParams?: any): Observable<ProductDetailDtoApiResponseDto>;

}
