/**
 * PaintDepotApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CalculateShippingDto } from '../model/models';
import { ShippingCalculationResultDtoApiResponseDto } from '../model/models';
import { ShippingRateDtoListApiResponseDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ShippingServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/shipping/calculate
     * @param calculateShippingDto 
     */
    apiShippingCalculatePost(calculateShippingDto?: CalculateShippingDto, extraHttpRequestParams?: any): Observable<ShippingCalculationResultDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/shipping/methods
     */
    apiShippingMethodsGet(extraHttpRequestParams?: any): Observable<ShippingRateDtoListApiResponseDto>;

}
