/**
 * PaintDepotApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AddToWishlistDto } from '../model/models';
import { ObjectApiResponseDto } from '../model/models';
import { WishlistDtoApiResponseDto } from '../model/models';
import { WishlistDtoListApiResponseDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface WishlistServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/wishlist
     */
    apiWishlistGet(extraHttpRequestParams?: any): Observable<WishlistDtoListApiResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/wishlist/items
     * @param addToWishlistDto 
     */
    apiWishlistItemsPost(addToWishlistDto?: AddToWishlistDto, extraHttpRequestParams?: any): Observable<WishlistDtoApiResponseDto>;

    /**
     * 
     * 
     * @endpoint delete /api/wishlist/items/{productId}
     * @param productId 
     */
    apiWishlistItemsProductIdDelete(productId: number, extraHttpRequestParams?: any): Observable<ObjectApiResponseDto>;

}
